# Generated by Django 4.2.27 on 2026-01-15 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_about_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='header',
            field=models.CharField(default=datetime.datetime(2026, 1, 15, 8, 47, 13, 132390, tzinfo=datetime.timezone.utc), max_length=40),
            preserve_default=False,
        ),
    ]
